### ISSUE TITLE
Multiple Requests to IBrowseServices<EndpointRegistrationModel>.NodeBrowseAsync result in exception

### ISSUE THREAD

**Issue by mma-mm** [Azure/azure-iiot-opc-ua#5]
Hi,

I'm using the supervisor client to access the opc device twin module from my module. I need to Browse multiple nodes, so i start several Tasks with NodeBrowseAsync at once. This sometimes works, sometimes it results in this Exception:

    Microsoft.Azure.Devices.Client.Exceptions.IotHubException: {"message":"Timed out waiting for device to respond to method request 9aabd6bb-d1a9-47ac-833f-ac040cb53b5f","exceptionMessage":"","status":0,"payload":null}
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
       at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.CallMethodAsync(String deviceId, String moduleId, String method, String payload, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.Default.ChunkMethodClient.CallMethodAsync(String deviceId, String moduleId, String method, Byte[] payload, String contentType, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.MethodClientEx.CallMethodAsync(IMethodClient client, String deviceId, String moduleId, String method, String json, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.CallServiceOnSupervisor[T,R](String service, EndpointRegistrationModel registration, T request)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.NodeValueReadAsync(EndpointRegistrationModel registration, ValueReadRequestModel request)
       at MyModule.Communication.Twincommunicator.GetValue(String nodeId)

Once this exception appears, it will appear for about a minute for any browse request or read request made. If some time passes until the next request, it works again.

Is there a limit, how many BrowseOperations can be queued or run in parallel or per second? If so, what is the limit?
The connection is made over the edge hub, so i don't think IoT-Hub-Throttling applies.
I don't think hardware is limiting here, due to 4 cores and 8GB RAM.

Thanks for your help

Matthias Mucha

**Comment by marcschier** [comment]
Hi Matthias, the way the client is implemented is that all access to the session is single threaded and there is only a single session per endpoint description.  This is so that even nano profile servers that support at Max 2 sessions at a time would most likely work.  However, each request has a default timeout of I believe a minute or so, which means requests queued to the session might time out before they had a time to get scheduled.  We will also eventually limit queue size and thus throttle requests. No matter timeout exception is probably not entirely well chosen here it is more of a client busy exception.  Workaround would be to use a single thread to issue your requests and retry these timeouts.  Due to the implementation multiple threads would not be faster anyway.

What is it you are looking to accomplish by doing all these browse operations?  Are you trying to grab the entire address space?

**Comment by mma-mm** [comment]
Kind of, yes. Thanks, so i will serialize the requests and try again.

**Comment by mma-mm** [comment]
I serialized the requests and inserted a break of 1 s between each request. The problem persists. The communication works again if the opc twin module is restarted though. So i guess the problem is there. I'll open an issue there.
